name: "ğŸ“ Regenerate README"
on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - resume.pdf
jobs:
    recompile-resume:
        runs-on: ubuntu-latest
        steps:
            - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
            - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"

            - name: Install deps
              run: |
                  sudo apt-get install poppler-utils--no-install-recommends

            - name: Check out repository code
              uses: actions/checkout@v3

            - name: PDF to png
              run: pdftoppm -png -singlefile resume.pdf resume

            - name: Create Pull Request
              id: cpr
              uses: peter-evans/create-pull-request@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  commit-message: "ğŸ—ï¸ Recompile resume"
                  committer: ${{github.repository_owner}} <${{ github.repository_owner }}@users.noreply.github.com>
                  author: ${{github.repository_owner}} <${{ github.repository_owner }}@users.noreply.github.com>
                  signoff: false
                  branch: regen-readme
                  delete-branch: true
                  title: "ğŸ“ Regenerate README"
                  body: |
                      The resume was recompiled by GitHub Action 'Recompile README'
                  labels: |
                      regeneration
                  reviewers: ${{ github.repository_owner }}
                  draft: false